spring.application.name=DatasoftLibrary

spring.datasource.url=jdbc:postgresql://dpg-d7fsb01j2pic73bpggj0-a.oregon-postgres.render.com/datasoft_library
spring.datasource.username=datasoft_library_user
spring.datasource.password=OOpQzuGpq5t6cT5RttLT4nkAcQ5JZizk
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

# jwt secret
jwt.secret.key=UltraMegaSuperDuperIncredibleChuckNorrisLevelSecretKey
# jwt exp time in milliseconds <- 15 days
jwt.time.expiration=1296000000